language: python
cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

install:
  - python setup.py develop
  - pip install -r requirements-test.txt
  # TODO: remove when openwisp-utils with isort 5 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

before_script:
  - ./run-qa-checks

script:
  - nose2 --with-coverage --coverage=netdiff

after_success:
  coveralls
